Chore/project popup
Reconfort/reconfort.github.io pull request #16
Opened 2023-08-02 19:15 UTC by Reconfort

2023-08-02 20:10 UTC, DuaneDave requested changes
Hi @Reconfort 👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ An array of object-specific too each project is present

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 20:10 UTC, DuaneDave commented on index.html
> +        </div> -->
A fundamental requirement for this milestone is that the section for the work cards is supposed to be empty because the cards would be generated dynamically with javascript and as such I recommend implementing the requirements as expected in order to satisfy its demands.

Furthermore, when I click the see project button, it doesn't fire the modal, I suggest going through your code again to ensure things are wired up correctly so as to spot the error and resolve it.

2023-08-02 23:15 UTC, rica213 requested changes
# 🟡 STATUS: REQUIRED CHANGES ♻️ 
Hi Reconfort, 
My name is Larissa. Your code reviewer 🥰

You have implemented the required changes from the previous reviewer. Thank you ❤️ 
However, there are some issues that I want you to fix. Kindly refer them in the comment section below 👇🏽 

<img src="https://media1.giphy.com/media/cfuL5gqFDreXxkWQ4o/giphy-downsized-medium.gif"/>

Happy coding!
## Highlights

Descriptive PR summary and title 💯 
Professional Documentation ✔️
No Linter errors ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


# Cheers, and Happy coding 🖥️

## If anything is not 100% clear, kindly mention me in your comment and I will reply ASAP 🤞

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 23:15 UTC, rica213 commented on main.js
> +            </ul>
- [ ] Kindly fix your tech stack because currently, they are not wrapping on a smaller size screen.  You can fix that by setting the flex-wrap to `wrap`. And kindly, remove the comas that separate the tech in order to follow the design provided in the Figma ❤️ 

Your design (width = 445px) 👇🏽 

![Screenshot from 2023-08-03 02-05-38](https://github.com/Reconfort/reconfort.github.io/assets/10439283/30529855-27ad-490f-9945-a1f3a89dc956)

2023-08-03 16:39 UTC, skyv26 approved these changes
## Hi @Reconfort, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGJhMzBhODJmYjQwOGJiYTYxNTllMzM4MzcxZDY2NDcyMTgwODUxMyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/IL4iTvQH0MjS/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Linters are green ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 17:14 UTC, merged